folder_in: /home/user2/tst
folder_out: /home/user2/out
folder_ext:  /home/user2/folder1
folder_ext2: /home/user2/folder2
folder_badarx: /home/user2/badarx

count: 5
size: 1M
host: localhost
user: user2
passwd: "11"
pkgname: p7zip-full
type: 7z